# Products related urls
from django.urls import path, include
from products.views import products, alt_dyno, body, bonnet, boot, brakes, brakes_fr, brakes_handbrake, bumpers, \
                           chassis, clutch, cooling, crankshaft, dashboard, door, drive_line, electrical, engine, exhaust, external, \
                           fuel, fuel_pipes, fuel_tank, gearbox, gearbox_mk4, gearbox_1500, hardtop, heating, hood, \
                           ignition, inner_body, inst_sw, interior, lamps, mouldings, oilsump, outer_body, overdrive, \
                           overdrive_j, rad_grill, ratings, road_wheels, seats, steering, suspension, trim_kits, windscreen, wshld_wipe_wash, wire_int

urlpatterns = [
    path('categories/', products, name='products'),
    path('alt_dyno/', alt_dyno, name='alt_dyno'),
    path('body/', body, name='body'),
    path('bonnet/', bonnet, name='bonnet'),
    path('boot/', boot, name='boot'),
    path('brakes/', brakes, name='brakes'),
    path('brakes_fr/', brakes_fr, name='brakes_fr'),
    path('brakes_handbrake/', brakes_handbrake, name='brakes_handbrake'),
    path('bumpers/', bumpers, name='bumpers'),
    path('chassis/', chassis, name='chassis'),
    path('clutch/', clutch, name='clutch'),
    path('cooling/', cooling, name='cooling'),
    path('crankshaft/', crankshaft, name='crankshaft'),
    path('dashboard/', dashboard, name='dashboard'),
    path('door/', door, name='door'),
    path('drive_line/', drive_line, name='drive_line'),
    path('electrical/', electrical, name='electrical'),
    path('engine/', engine, name='engine'),
    path('exhaust/', exhaust, name='exhaust'),
    path('external/', external, name='external'),
    path('fuel/', fuel, name='fuel'),
    path('fuel_pipes/', fuel_pipes, name='fuel_pipes'),
    path('fuel_tank/', fuel_tank, name='fuel_tank'),
    path('gearbox/', gearbox, name='gearbox'),
    path('gearbox_mk4/', gearbox_mk4, name='gearbox_mk4'),
    path('gearbox_1500/', gearbox_1500, name='gearbox_1500'),
    path('hardtop/', hardtop, name='hardtop'),
    path('heating/', heating, name='heating'),
    path('hood/',hood, name='hood'),
    path('ignition/', ignition, name='ignition'),
    path('inner_body/', inner_body, name='inner_body'),
    path('inst_sw/', inst_sw, name='inst_sw'),
    path('interior/', interior, name='interior'),
    path('lamps/', lamps, name='lamps'),
    path('mouldings/', mouldings, name='mouldings'),
    path('oilsump/', oilsump, name='oilsump'),
    path('overdrive/', overdrive, name='overdrive'),
    path('overdrive_j/', overdrive_j, name='overdrive_j'),
    path('outer_body/', outer_body, name='outer_body'),
    path('rad_grill/', rad_grill, name='rad_grill'),
    path('ratings/', ratings, name='ratings'),
    path('road_wheels/', road_wheels, name='road_wheels'),
    path('seats/', seats, name='seats'),
    path('steering/', steering, name='steering'),
    path('suspension/', suspension, name='suspension'),
    path('trim_kits/', trim_kits, name='trim_kits'),
    path('wshld_wipe_wash/', wshld_wipe_wash, name='wshld_wipe_wash'),
    path('windscreen/', windscreen, name='windscreen'),
    path('wire_int/', wire_int, name='wire_int'),
]
